from typing import Literal


SCHEMES = Literal["http", "https"]
DEFAULT_HTTP_PORT = 80
DEFAULT_HTTPS_PORT = 443
PORTS = Literal[80, 443]
PORT_BY_SCHEME = {"http": DEFAULT_HTTP_PORT, "https": DEFAULT_HTTPS_PORT}
ALPN_H2 = "h2"

RECV_BUFFER_SIZE = 1000
ZERO_SETTINGS = 0

NULL_SETTINGS_PTR = None
NULL_PRIORITY = None
NULL_USER_DATA_PTR = None
NULL_DATA_PROVIDER = None

NGHTTP2_NO_ERROR = 0
NGHTTP2_FLAG_NONE = 0
NGHTTP2_NV_FLAG_NONE = 0

NO_DATA_SLEEP = 0.0001
TIMEOUT = 10
